version: "3"

vars: {}
dotenv: [".env"]

tasks:
  # 初期環境構築用タスク
  init:
    desc: Initialize project.
    deps:
      - clean
    cmds:
      - git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
      - task: switch-webui-version
      - npm install -D
  switch-webui-version:
    desc: Switch webui version.
    dir: stable-diffusion-webui
    cmds:
      - git switch -c v1.7.0 tags/v1.7.0
  clean:
    # rmは環境によって利用できないのでgit cleanを利用する。
    desc: Clean files.
    cmds:
      - git clean -fdx stable-diffusion-webui

  # ローカルサーバー起動用タスク
  webui:
    desc: Start webui.
    dir: stable-diffusion-webui
    cmds:
      - cmd: '.\\webui-user.bat'
        platforms:
          - "windows"

  # linter, formatter
  lint:
    desc: Lint files.
    cmds:
      - dprint check
      - npx prettier --check "**/*.{yml,yaml}"
      - npx cspell lint .
  format:
    desc: Format files.
    cmds:
      - dprint fmt
      - npx prettier --write "**/*.{yml,yaml}"
